package com.traveling.salesman.problem.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

public class TSPMenu extends JFrame {

    private JTextField thisIsATextTextField;
    private JPanel mainPanel;
    private JTextPane txtDescription;
    private JLabel labelMutate;
    private JLabel labelCrossover;
    private JLabel labelPath;
    private JTextField txtPath;
    private JSlider sliderMutProb;
    private JTextPane txtMutVer1;
    private JTextPane txtCrossVer1;
    private JRadioButton radBtnMutVer1;
    private JRadioButton radBtnCrossVer1;
    private JRadioButton radBtnCrossVer2;
    private JRadioButton radBtnMutVer2;
    private JTextPane txtCrossVer2;
    private JTextPane txtMutVer2;
    private JLabel labelMutVer;
    private JLabel labelCrossVer;
    private JRadioButton radBtnCrossVer3;
    private JTextPane txtCrossVer3;
    private JPanel settingsPanel;
    private JTextPane txtConsolOutput;
    private JScrollPane consolScrollPane;
    private JPanel panelMutProb;
    private JTextField txtMutProbValue;
    private JSlider sliderMutRange;
    private JLabel labelMutRange;
    private JTextField txtMutRangValue;
    private JPanel panelMutRange;
    private JButton btnStart;
    private JLabel labelPop;
    private JTextPane textPane1;

    public static void main(String[] args) {
        TSPMenu menu = new TSPMenu();

    }

    public TSPMenu() {
        setContentPane(mainPanel);
        setTitle("TSP MENU");
        setSize(1000, 800);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);


        //Setting up txtMutProb and txtMutrange
        txtMutProbValue.setText(String.valueOf(sliderMutProb.getValue()));
        txtMutRangValue.setText(String.valueOf(sliderMutRange.getValue()));


        //Setting up action listener
        btnStart.addActionListener(action -> {

        });
        sliderMutProb.addChangeListener(action -> {
            txtMutProbValue.setText(String.valueOf(sliderMutProb.getValue()));
        });
        sliderMutRange.addChangeListener(action -> {
            txtMutRangValue.setText(String.valueOf(sliderMutRange.getValue()));
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 1, new Insets(3, 3, 3, 3), -1, -1));
        mainPanel.setAlignmentX(0.0f);
        mainPanel.setAlignmentY(1.0f);
        mainPanel.setAutoscrolls(false);
        mainPanel.setBackground(new Color(-2565928));
        mainPanel.setMaximumSize(new Dimension(-1, -1));
        mainPanel.setMinimumSize(new Dimension(700, 700));
        mainPanel.setPreferredSize(new Dimension(1000, 800));
        consolScrollPane = new JScrollPane();
        consolScrollPane.setEnabled(true);
        consolScrollPane.setMinimumSize(new Dimension(-1, 100));
        consolScrollPane.setName("");
        consolScrollPane.setPreferredSize(new Dimension(-1, 100));
        consolScrollPane.setToolTipText("");
        mainPanel.add(consolScrollPane, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        txtConsolOutput = new JTextPane();
        txtConsolOutput.setEditable(false);
        txtConsolOutput.setMargin(new Insets(5, 5, 5, 5));
        txtConsolOutput.setMinimumSize(new Dimension(-1, 100));
        txtConsolOutput.setPreferredSize(new Dimension(-1, 100));
        txtConsolOutput.setText("Dies ist ein langer Text\n- mit vielen Absätzen\n- mit vielen Absätzen\n- mit vielen Absätzen\n- mit vielen Absätzen");
        consolScrollPane.setViewportView(txtConsolOutput);
        txtDescription = new JTextPane();
        txtDescription.setBackground(new Color(-2565928));
        txtDescription.setMaximumSize(new Dimension(-1, -1));
        txtDescription.setPreferredSize(new Dimension(-1, 22));
        txtDescription.setText(this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.txtDescription"));
        mainPanel.add(txtDescription, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(100, 100), new Dimension(100, 50), null, 0, false));
        settingsPanel = new JPanel();
        settingsPanel.setLayout(new GridLayoutManager(11, 3, new Insets(0, 5, 5, 5), -1, -1));
        mainPanel.add(settingsPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 400), new Dimension(-1, 500), null, 0, false));
        settingsPanel.setBorder(BorderFactory.createTitledBorder(null, "Settings", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        labelCrossover = new JLabel();
        this.$$$loadLabelText$$$(labelCrossover, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.label.crossover"));
        settingsPanel.add(labelCrossover, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(220, 16), null, 0, false));
        labelMutate = new JLabel();
        this.$$$loadLabelText$$$(labelMutate, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.label.mutate"));
        settingsPanel.add(labelMutate, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(220, 16), null, 0, false));
        labelPath = new JLabel();
        labelPath.setAlignmentX(0.5f);
        this.$$$loadLabelText$$$(labelPath, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.label.path"));
        settingsPanel.add(labelPath, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(220, 16), null, 0, false));
        txtPath = new JTextField();
        settingsPanel.add(txtPath, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(220, 34), null, 0, false));
        labelMutVer = new JLabel();
        this.$$$loadLabelText$$$(labelMutVer, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.label.mutateVer"));
        settingsPanel.add(labelMutVer, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(219, 16), null, 0, false));
        labelCrossVer = new JLabel();
        this.$$$loadLabelText$$$(labelCrossVer, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.label.crossoverVer"));
        settingsPanel.add(labelCrossVer, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtMutVer1 = new JTextPane();
        txtMutVer1.setEditable(false);
        txtMutVer1.setText("");
        settingsPanel.add(txtMutVer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        txtCrossVer1 = new JTextPane();
        txtCrossVer1.setEditable(false);
        txtCrossVer1.setText("");
        settingsPanel.add(txtCrossVer1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        radBtnMutVer1 = new JRadioButton();
        this.$$$loadButtonText$$$(radBtnMutVer1, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.radBox.mutateVer.first"));
        settingsPanel.add(radBtnMutVer1, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radBtnCrossVer1 = new JRadioButton();
        this.$$$loadButtonText$$$(radBtnCrossVer1, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.radBox.crossoverVer.first"));
        settingsPanel.add(radBtnCrossVer1, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radBtnCrossVer2 = new JRadioButton();
        this.$$$loadButtonText$$$(radBtnCrossVer2, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.radBox.crossoverVer.second"));
        settingsPanel.add(radBtnCrossVer2, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        radBtnMutVer2 = new JRadioButton();
        this.$$$loadButtonText$$$(radBtnMutVer2, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.radBox.mutateVer.second"));
        settingsPanel.add(radBtnMutVer2, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCrossVer2 = new JTextPane();
        txtCrossVer2.setEditable(false);
        settingsPanel.add(txtCrossVer2, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        txtMutVer2 = new JTextPane();
        txtMutVer2.setEditable(false);
        txtMutVer2.setText("");
        settingsPanel.add(txtMutVer2, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        radBtnCrossVer3 = new JRadioButton();
        this.$$$loadButtonText$$$(radBtnCrossVer3, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.radBox.crossoverVer.third"));
        settingsPanel.add(radBtnCrossVer3, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCrossVer3 = new JTextPane();
        txtCrossVer3.setEditable(false);
        settingsPanel.add(txtCrossVer3, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        panelMutProb = new JPanel();
        panelMutProb.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        settingsPanel.add(panelMutProb, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.label.mutateProb"));
        panelMutProb.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtMutProbValue = new JTextField();
        txtMutProbValue.setEditable(false);
        panelMutProb.add(txtMutProbValue, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(50, 34), new Dimension(50, 34), null, 0, false));
        sliderMutRange = new JSlider();
        sliderMutRange.setMaximum(10);
        sliderMutRange.setValue(5);
        settingsPanel.add(sliderMutRange, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panelMutRange = new JPanel();
        panelMutRange.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        settingsPanel.add(panelMutRange, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        labelMutRange = new JLabel();
        this.$$$loadLabelText$$$(labelMutRange, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.label.mutateRange"));
        panelMutRange.add(labelMutRange, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtMutRangValue = new JTextField();
        txtMutRangValue.setEditable(false);
        txtMutRangValue.setText("");
        panelMutRange.add(txtMutRangValue, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(50, 34), new Dimension(50, 34), null, 0, false));
        sliderMutProb = new JSlider();
        sliderMutProb.setSnapToTicks(false);
        sliderMutProb.setValue(50);
        sliderMutProb.setValueIsAdjusting(false);
        settingsPanel.add(sliderMutProb, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(219, 24), null, 0, false));
        btnStart = new JButton();
        this.$$$loadButtonText$$$(btnStart, this.$$$getMessageFromBundle$$$("com/traveling/salesman/problem/res/Strings", "string.btn.start"));
        settingsPanel.add(btnStart, new GridConstraints(10, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    private static Method $$$cachedGetBundleMethod$$$ = null;

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadButtonText$$$(AbstractButton component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}